version: '3.4'

services:
  cascadeapi:
    image: ${DOCKER_REGISTRY-}cascadeapi
    container_name: CascadeAPI
    ports:
      - 8081:443
    environment:
      ASPNETCORE_URLS: https://+
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_ENVIRONMENT: "Development"
    build:
      context: .
      dockerfile: CascadeAPI/Dockerfile
    depends_on:
      - sqlserverdb
      - redis
      - rabbitmq
      - ftpserver

  sqlserverdb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=z@malo_Dap0g1nem#

  redis:
    container_name: RedisContainer
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    container_name: RabbitMQContainer
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672

  ftpserver:
    image: bogem/ftp
    container_name: FTPServerContainer
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    environment:
      - FTP_USER=testov3
      - FTP_PASS=prototype
      - PASV_ADDRESS=127.0.0.1
    volumes:
      - /host/folder:/home/vsftpd
    restart: always

volumes:
  ftp_data:
